### ISSUE TITLE
Update About with copy in 8-10 folder in Dropbox

### ISSUE THREAD

**Issue by circa1977** [clearbold/boardpackager#13]

**Comment by circa1977** [comment]
Let's copy the About page you've built as styleguide.html, leave it in the repository. Thanks!

**Comment by circa1977** [comment]
The punchlist also references a Google doc with About content, too. I'm assuming the 8-10/"ming" file is a team member bio.

Punchlist for content: https://dl.dropboxusercontent.com/u/2953460/punchlist.html/index.html

**Comment by circa1977** [comment]
From BoardPackager:

> We really like how the side nav stays there on the FAQ page. The About Us has the same function, but there's really only two sections, does it still make sense? Trust you on that. 

@sodevious Any questions about how this page is organized from a content perspective? Use your discretion on whether the in-page nav should go away there. Thanks!

**Comment by sodevious** [comment]
@aarontw what should we do about the image?

**Comment by sodevious** [comment]
Also could this layout work? https://clearbold.github.io/boardpackager/about/

**Comment by aarontw** [comment]
@sodevious Yes that layout works! I think for the Jim image (https://www.dropbox.com/sh/ue8tbvfxiv2ivgj/AAARyxDHKsR3rzmqTIyVixx0a?dl=0) — yes, its vertical and blurry, which is not ideal. What about left-aligning it and scaling it to 50% of the width of the content column? Not great, but…not terrible?

![image](https://cloud.githubusercontent.com/assets/1452630/17636849/da0260ea-60ad-11e6-9aa2-5be6a5244dd2.png)

**Comment by sodevious** [comment]
@aarontw would this work? https://clearbold.github.io/boardpackager/about/

**Comment by aarontw** [comment]
looks good @sodevious ! Can you please add about 20px padding above and to the right of the image? Otherwise good by me. Thank you!
