### ISSUE TITLE
Update "For...", Security pages with copy

### ISSUE THREAD

**Issue by circa1977** [clearbold/boardpackager#15]
Here's the punchlist for most of the content, including links to Google Docs copy decks:

https://dl.dropboxusercontent.com/u/2953460/punchlist.html/index.html

**Comment by sodevious** [comment]
@circa1977 @aarontw I wasn't sure whether to use the teaser content in the hero or in the page body:

https://clearbold.github.io/boardpackager/brokers/
https://clearbold.github.io/boardpackager/property-managers/
https://clearbold.github.io/boardpackager/applicants/
https://clearbold.github.io/boardpackager/service-providers/
https://clearbold.github.io/boardpackager/boards/

**Comment by aarontw** [comment]
@sodevious thanks for checking in on this—I believe the way you have it for https://clearbold.github.io/boardpackager/boards/ is correct—does that format work across the board?

**Comment by sodevious** [comment]
Yep, updated but the only exception is Property Managers were there is copy in both the header and content https://clearbold.github.io/boardpackager/property-managers/

**Comment by aarontw** [comment]
@sodevious right, thanks for clarifying—it looks good as is, thank you. 
I'm seeing a broken img link for epay on https://clearbold.github.io/boardpackager/property-managers/

Also will note for myself that I could provide a different icon for 'track', as it looks small relative to the others. Maybe if I lose a dot?

Thanks,
Aaron
