### ISSUE TITLE
Apply and E-pay icons are the same

### ISSUE THREAD

**Issue by sodevious** [clearbold/boardpackager#18]
<img width="413" alt="screenshot 2016-08-12 15 09 36" src="https://cloud.githubusercontent.com/assets/915966/17634087/d6c9ab36-609e-11e6-8605-66c913c6b724.png">

**Comment by aarontw** [comment]
Thanks for catching that @sodevious — fixed:
![image](https://cloud.githubusercontent.com/assets/1452630/17637152/b201a040-60af-11e6-83a5-e51c707e14ab.png)
