### ISSUE TITLE
New 'track' icon that is smaller

### ISSUE THREAD

**Issue by aarontw** [clearbold/boardpackager#19]
'Track' icon is too small relative to the others:
![image](https://cloud.githubusercontent.com/assets/1452630/17645847/f756f53a-617e-11e6-8b81-062795222112.png)

**Comment by sodevious** [comment]
@aarontw I think you mentioned loosing a circle in the track icon? That would work if you want to send a new one!

**Comment by aarontw** [comment]
Hey @sodevious — perfect, thank you!
Here is the link to the new @2x PNG + SVG in our Dropbox:
https://www.dropbox.com/sh/z9vbljl1qe1skqw/AAAmxTh3VfuVhUlhEWV7QCmGa?dl=0
