### ISSUE TITLE
Document image treatments?

### ISSUE THREAD

**Issue by circa1977** [clearbold/boardpackager#21]
Hi, @sodevious! Looking at the new header image @aarontw posted for Service Providers, I'm not looking for how to produce new versions of those with the same quality and grayscale tint. Can you document that in the README or somewhere in the site for all images produced? Thanks!

**Comment by sodevious** [comment]
@circa1977 Added to the DB: https://www.dropbox.com/s/414smecnsz3dumk/header-overlay.psd?dl=0
