### ISSUE TITLE
Security header image has some bleed along the left edge

### ISSUE THREAD

**Issue by circa1977** [clearbold/boardpackager#28]
@aarontw Was this in the original image or in production? This is low priority against the missing FAQ & Broker headers.

https://clearbold.github.io/boardpackager/assets/images/headers/bp-security-header.jpg

**Comment by aarontw** [comment]
While Jeannie decides on the Broker + FAQ images, I'm looking at the other header images. These 3 have bleed I notice on the top, I will re-crop:

https://github.com/clearbold/boardpackager/blob/gh-pages/assets/images/headers/bp-faq-header.jpg

https://github.com/clearbold/boardpackager/blob/gh-pages/assets/images/headers/bp-property-managers-header.jpg

https://github.com/clearbold/boardpackager/blob/gh-pages/assets/images/headers/bp-faq-header.jpg

I put all of the current headers @sodevious exported from PS here:
https://www.dropbox.com/sh/kbdtdv4ddmnr8uw/AACTPb85csguxeZ0N2tZWNm9a?dl=0

Will create a new folder w/ today's exports

**Comment by aarontw** [comment]
Revised header images with fixed bleed issues:

Boards
https://www.dropbox.com/s/5qkqn63j3qc5m02/bp-board-header.r2.jpg?dl=0

Property Managers
https://www.dropbox.com/s/c8l7x5ixiy4hgt9/bp-property-managers-header.r2.jpg?dl=0

Security
https://www.dropbox.com/s/5sqess9fa172dag/bp-security-header.r2.jpg?dl=0

**Comment by sodevious** [comment]
Thanks @aarontw, updated!
