### ISSUE TITLE
Bot-proof email addresses

### ISSUE THREAD

**Issue by circa1977** [clearbold/boardpackager#3]
> Please adjust any email addresses within the copy to prevent bot emails such as using underscores or a space around any @ –trust your team to know what's best for this, we are not particular to one style or another.

@sodevious I'm thinking a JavaScript solution that writes them on the fly? I've used the [email obfuscator](http://www.albionresearch.com/misc/obfuscator.php) before.

**Comment by sodevious** [comment]
@circa1977 Will this work? https://github.com/clearbold/boardpackager/commit/1a1c61001e2f564411a099a16efe4bfafb29c3dc

**Comment by circa1977** [comment]
I'm thinking we need a solution that uses `document.write` (or equivalent) so that it's not available at all in the markup. They seemed pretty intent on having something robust in place. Thanks!

**Comment by sodevious** [comment]
Hi @circa1977, what do you think about this https://github.com/clearbold/boardpackager/commit/0e81b6db2a8070e3dea690b56dc3e53212580886?

No addresses get served in the markup, jQuery parses the empty `<a>` links and uses the data attribute to create the email address.

**Comment by circa1977** [comment]
👍
