### ISSUE TITLE
iOS 8 section labels/highlight

### ISSUE THREAD

**Issue by circa1977** [clearbold/boardpackager#32]
> On iOS 8 devices section labels (Left panel) fail to highlight after tapping on it in portrait mode.

Let me know if you can track this down? It's 10% of the current market. https://developer.apple.com/support/app-store/

**Comment by sodevious** [comment]
@circa1977 Just to clarify, they are referring to the nav slideout here, right?

**Comment by circa1977** [comment]
I'm not sure Jeannie would even have the answer to that without going back to the QA firm. Is it something you can reproduce there before going back two hops? Thanks!

**Comment by circa1977** [comment]
> In the same vein as this issue, #32 is kind of a grey area because the links only highlight on hover and hover doesn't really exist on mobile.

So they're saying, "you've got :hover states showing on mobile, and that's not really working, but your :hover states aren't showing here?"

That, to me, is a non-issue, especially with a 10% audience.

**Comment by circa1977** [comment]
I assume the media query solution to #36 would render this moot?

**Comment by sodevious** [comment]
Yes @circa1977 it would be a moot point if we go the media query route

**Comment by circa1977** [comment]
Let's go ahead with this. We've got the MacBook Air as a non-touch/hover device at 1366 by 768, and the iPad Pro as a touch/non-hover device at 2732-by-2048 resolution at 264 pixels per inch (ppi), which should be 1366 x 1024? So that's the gray area we want to try to discern.
