### ISSUE TITLE
Nav links after nav'ing back

### ISSUE THREAD

**Issue by circa1977** [clearbold/boardpackager#36]
> Field labels / options / hyperlinks remain selected on returning back to the page after section. (Observe mostly on iOS devices and few android devices)

I'm assuming this is `:active` / `:visited` states? Does this make sense to you?

**Comment by sodevious** [comment]
Testing nav link states in the inspector and on my phone, I'm thinking by "selected" they mean the link turns orange. I saw this behavior when tapping & dragging – assuming the device registers the tap as a hover. 

Or could they be talking about form pages? We might need clarification on this one @circa1977

**Comment by circa1977** [comment]
Ah, thanks for that. I think they mean `:focus` states, but I'm not sure you can reset a `:focus` state when you hit the back button?

**Comment by circa1977** [comment]
Does this help?

http://stackoverflow.com/questions/10642953/mobile-safari-links-retains-focus-after-touch

**Comment by circa1977** [comment]
I mean, we don't want to cover hover states to JS in no way am I suggesting *that*.

**Comment by circa1977** [comment]
A friend says:

> Maybe a small JS thing that clears the focus of all links.

Maybe just toss something in `document.ready()` to reset focus on all `a`, `label`, etc on each page load to appease the QA gods?

**Comment by sodevious** [comment]
Hmm, `.blur` will unbind :focus, but not :hover which is causing the issue. 

Googling seems to only yield solutions that require modernizr, or only activating hover styles on larger devices with a media query.

**Comment by circa1977** [comment]
> Googling seems to only yield solutions that require modernizr, or only activating hover styles on larger devices with a media query.

I like those two options. Let me bounce it back to Jeannie.

**Comment by sodevious** [comment]
Sounds good, though I think #2 is better because it seems unnecessary to load in modernizr on every page for something so small.

**Comment by circa1977** [comment]
Definitely advocating # 2 rather than introducing Modernizr at this point. It's just that screen dimensions are an unreliable touch indicator, too. Think iPad Pro vs. MacBook Air. I'm offering to drop it as an issue, or go that route. Stay tuned!

**Comment by sodevious** [comment]
In the same vein as this issue,  #32 is kind of a grey area because the links only highlight on hover and hover doesn't really exist on mobile.

**Comment by circa1977** [comment]
See https://github.com/clearbold/boardpackager/issues/32#issuecomment-242505919
