### ISSUE TITLE
Service Provider page image change

### ISSUE THREAD

**Issue by circa1977** [clearbold/boardpackager#37]
@sodevious @aarontw Jeannie has requested an image change on the Board page and provided the following image. I'm not sure if it requires optimization or already exists?

> Can you change the first icon from a key to documents, png attached.

![icon](https://cloud.githubusercontent.com/assets/49657/17979047/c653324a-6ac6-11e6-8c3e-01646a9cd726.png)

**Comment by sodevious** [comment]
I'm not seeing a key, is this what she was referencing?  @circa1977 

<img width="597" alt="screen shot 2016-08-25 at 2 02 54 pm" src="https://cloud.githubusercontent.com/assets/915966/17980313/ad17ae54-6acc-11e6-88a0-717e0cb54422.png">

**Comment by circa1977** [comment]
I'll ask so that we're not guessing – Stay tuned!

**Comment by circa1977** [comment]
Here you go :)

> Excellent question, I messed that up. It's actually on the Service Provider page. There's a key now for "Get Docs" and it just seems a little weird. And now we have a few more icons that Aaron and I did together and I think that will work better there.

**Comment by sodevious** [comment]
Interestingly enough the document icon never made it into the repo or the dropbox!
