### ISSUE TITLE
Add a bit of padding to lefthand nav menu

### ISSUE THREAD

**Issue by circa1977** [clearbold/boardpackager#4]
When I scroll the lefthand nav menu on my laptop, there's only about 1em line-height at the bottom below the last link, which is covered by Firefox's status bar. Let's double or triple that **or**, perhaps preferably, make it match the space at the top above the X. Thanks!

**Comment by sodevious** [comment]
@circa1977 

Hi Mark,

Can you send me a screenshot? I'm seeing about 100px of space between the bottom of the navigation and the last link: https://www.dropbox.com/s/k160vyxpzxuljn6/Screenshot%202016-08-05%2015.55.00.png?dl=0

I'll add more regardless!

**Comment by circa1977** [comment]
This is all I get in Firefox :(

<img width="929" alt="screen shot 2016-08-05 at 4 02 49 pm" src="https://cloud.githubusercontent.com/assets/49657/17449072/1829aabe-5b26-11e6-90a8-26330d5c954f.png">

**Comment by circa1977** [comment]
(2016 MBP 15")

**Comment by sodevious** [comment]
Oh I see it now in Firefox too, strange!
