### ISSUE TITLE
Updating the orange color

### ISSUE THREAD

**Issue by circa1977** [clearbold/boardpackager#5]
We need to swap the orange that's used with a new value. From BoardPackager:

> They changed the Orange on the platform to F68A41 / R246/ G138/ B65. [Platform style guide attached.]

From Aaron:

> I'll need to re-export the SVGs/PNGs of the icons w/ that new # value baked in. If the filenames are the same that shouldn't be much time on your end to implement, right?

**Comment by sodevious** [comment]
@aarontw Images shouldn't be a problem to swap in!
