### ISSUE TITLE
The arrow on the Request a Demo button is wrapping on my iPhone 5c

### ISSUE THREAD

**Issue by circa1977** [clearbold/boardpackager#7]
Maybe we put a `span` around " a " and suppress that at the 320px breakpoint so it fits? So it becomes "Request Demo" on the smallest screens?

Thoughts, @aarontw? And then assign to Nicole?

**Comment by aarontw** [comment]
Hey @circa1977 !
Mine is looking like this @ 360:
![image](https://cloud.githubusercontent.com/assets/1452630/17560080/b4cf2878-5eee-11e6-854f-d50dd5ea6c72.png)

At 320, yes @sodevious could this be reduced to "Request Demo" to avoid wrap issues?

**Comment by circa1977** [comment]
![photo aug 10 11 38 09 am](https://cloud.githubusercontent.com/assets/49657/17560157/f8d89e8c-5eee-11e6-9657-770f089cee85.png)

We just need to make sure we're bulletproofing this one.

**Comment by aarontw** [comment]
Yep I see that, thanks @circa1977 !

@sodevious lets try **Request Demo** and **Request Demo ->** if that somehow fits @ 320 width.

Thanks!

**Comment by sodevious** [comment]
Fixed: <img width="428" alt="screenshot 2016-08-10 12 18 53" src="https://cloud.githubusercontent.com/assets/915966/17561554/a09ec312-5ef4-11e6-8459-47447447ad8e.png">
