### ISSUE TITLE
The left nav overlay feels a bit awkward to me on my iPhone 5c

### ISSUE THREAD

**Issue by circa1977** [clearbold/boardpackager#8]
It's centered within the screen, but feels too far from the left edge. Should this be tightened up on the left in a 320px viewport?

@aarontw Want to review and assign any tweaks to Nicole?

**Comment by aarontw** [comment]
Hey @circa1977 — I'm personally OK with the way its working currently. The padding is consistent to the left/right of the nav items. Can you post your screengrab on your phone?

![image](https://cloud.githubusercontent.com/assets/1452630/17560036/7a88b260-5eee-11e6-83eb-14afdb114a14.png)

http://design.google.com/resizer/#device=handset&url=https%3A%2F%2Fclearbold.github.io%2Fboardpackager%2Fproperty-managers%2F&width=600

**Comment by circa1977** [comment]
![photo aug 10 11 36 00 am](https://cloud.githubusercontent.com/assets/49657/17560090/bbe94c9c-5eee-11e6-9496-08bfafeb28a5.png)

I have less space to the right of the X than you, and if that comes over to the left based on right alignment, it's intersecting with the menu's space.

**Comment by aarontw** [comment]
Ah thats @ 320, thanks.

What if we reduce that nav div width to 320 for mobile breakpoint, i.e.:
![image](https://cloud.githubusercontent.com/assets/1452630/17560288/83c3c760-5eef-11e6-95ca-979677a161bc.png)

@sodevious does that work for you?

**Comment by sodevious** [comment]
I ended up making the nav fluid based below a certain width so that there is equal spacing, can you take a look and let me know if it feels better? @aarontw @circa1977 

<img width="374" alt="screenshot 2016-08-10 12 53 15" src="https://cloud.githubusercontent.com/assets/915966/17562645/ac8fc784-5ef9-11e6-96f6-9c2f668038b0.png">

**Comment by circa1977** [comment]
That feels better! I think it was the X alignment being off more than it was the lefthand spacing. Thanks!
