### ISSUE TITLE
Form submit buttons are smaller than CTAs

### ISSUE THREAD

**Issue by circa1977** [clearbold/boardpackager#9]
@aarontw Was this intentional? Do you want these to be smaller or should their height match that of the CTA buttons? Assign any changes to Nicole or close this one? Thanks!

**Comment by aarontw** [comment]
Hi @sodevious + @circa1977 

New **security** icon, 2x PNG + SVG here:
https://www.dropbox.com/sh/nfxy827hvba3dw1/AABbnuNFfLt8qKgVjNnlxWA3a?dl=0

**Comment by circa1977** [comment]
That reply is for #11 :)

**Comment by aarontw** [comment]
These were intended to be uniform, 36px height
![image](https://cloud.githubusercontent.com/assets/1452630/17559730/419f7660-5eed-11e6-8bb5-c2af8d2c992e.png)

**Comment by circa1977** [comment]
@sodevious Can you double-check the form buttons? Thanks!

**Comment by sodevious** [comment]
@circa1977 Can you show me what you're seeing? This is what I've got 
![buttons](https://cloud.githubusercontent.com/assets/915966/17562128/57b91956-5ef7-11e6-9520-589c23be4524.jpg)

**Comment by circa1977** [comment]
![screen shot 2016-08-10 at 12 41 01 pm](https://cloud.githubusercontent.com/assets/49657/17562197/bfe66290-5ef7-11e6-80ce-9136fed53bfd.png)

It's slight. That's two Firefox windows side by side. The form buttons just feel tight.

**Comment by circa1977** [comment]
I take it back. It's an optical delusion. xScope shows them both at 76px tall. Closing!
